# 6. root directory에 serverless.yaml 파일 추가 후, 아래 내용 작성

service: c-nest # project name
org: jongwanra
app: c-nest

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-1

plugins:
  - serverless-offline

package:
  exclude:
    - .git/**
    - src/**
    - test/**
    - e2e/**
    - nodemon.json
    - README.md

functions:
  index:
    handler: dist/index.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any
  author:
    handler: dist/index.handler
    events:
      - http: # Add API Gate Way
          method: any
          path: api/author
          # integration: lambda
# book:
#   handler: src/lambda.handler
#   events:
#     - http:
#         method: any
#         path: /api/book
#         cors: true
